<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNuzc9aw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNuzc9aw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNuzc9aw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNuzc9aw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNuzc9aw\appProdProjectContainer(array(
    'container.build_hash' => 'Nuzc9aw',
    'container.build_id' => '538514b7',
    'container.build_time' => 1558247771,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNuzc9aw');
